name: Validate push
on: [push]

jobs:
  install:
    strategy:
      matrix:
        symfony-version: [ 4.4, 5.4 ]
        php-version: [ 7.4, 8.1 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.symfony-version }}-${{ matrix.php-version }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.symfony-version }}-${{ matrix.php-version }}

      - name: Setup flex
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          command: global require --no-progress --no-scripts --no-plugins symfony/flex

      - uses: php-actions/composer@v6
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
        with:
          php_version: ${{ matrix.php-version }}
          command: install --no-interaction --no-scripts --ansi --no-progress --prefer-dist

  phpstan:
    strategy:
      matrix:
        include:
          - symfony-version: 4.4
            php-version: 7.4
          - symfony-version: 5.4
            php-version: 8.1

    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.symfony-version }}-${{ matrix.php-version }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.symfony-version }}-${{ matrix.php-version }}

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php_version: ${{ matrix.php-version }}
          ini-values: pcov.directory=.
          coverage: pcov

      - name: PHPStan
        run: |
          vendor/bin/phpstan --ansi --no-progress
          
  php-cs-fixer:
    strategy:
      matrix:
        include:
          - symfony-version: 4.4
            php-version: 7.4
          - symfony-version: 5.4
            php-version: 8.1

    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.symfony-version }}-${{ matrix.php-version }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.symfony-version }}-${{ matrix.php-version }}

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php_version: ${{ matrix.php-version }}
          ini-values: pcov.directory=.
          coverage: pcov

      - name: PHP-CS-Fixer
        run: |
          vendor/bin/php-cs-fixer fix --config ./.php-cs-fixer.dist.php --dry-run --diff --ansi

  test:
    strategy:
      matrix:
        symfony-version: [ 4.4, 5.4 ]
        php-version: [ 7.4, 8.1 ]

    runs-on: ubuntu-latest
    needs:
      - phpstan
      - php-cs-fixer

    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.symfony-version }}-${{ matrix.php-version }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.symfony-version }}-${{ matrix.php-version }}

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php_version: ${{ matrix.php-version }}
          ini-values: pcov.directory=.
          coverage: pcov

      - name: PHPUnit
        run: |
          vendor/bin/phpunit --coverage-cobertura artifacts/code-coverage-cobertura.xml
